---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportes-deployment
  labels:
    app: reportes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reportes
  template:
    metadata:
      labels:
        app: reportes
    spec:
      containers:
        - name: reportes
          image: reportes-service
          imagePullPolicy: Never
          env:
            - name: SENSORES_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: gas-secrets
                  key: sensores_service_url
            - name: PYTHONUNBUFFERED
              value: "0"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 40m
              memory: 40Mi
            limits:
              cpu: 60m
              memory: 60Mi

---
apiVersion: v1
kind: Service
metadata:
  name: reportes-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: reportes
