---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensores-deployment
  labels:
    app: sensores
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensores
  template:
    metadata:
      labels:
        app: sensores
    spec:
      containers:
        - name: sensores
          image: sensores-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: sensores-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: sensores
